version: 0.2

phases:
  build:
    commands:
      - echo "Listing files"
      - ls -la
      - echo "Creating correct lambda package"
      - zip -j function.zip lambda_fun.py

artifacts:
  files:
    - function.zip