version: 0.2

phases:
  build:
    commands:
      - echo "Checking files..."
      - ls -la
      - echo "Creating clean Lambda zip..."
      - zip -r function.zip lambda_fun.py

artifacts:
  files:
    - function.zip